version: '3.0'
services:
  dbtest:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /Users/khoa/SourceCode/ed67cea10a0c58cbf377a25972805dfd5f58b8cbc1da19a78bb8d14c08f172a7/_data/:/var/lib/postgresql/data
#      - /Users/khoa/SourceCode/data/_data/:/var/lib/postgresql/
    command:
      - "postgres"
      - "-c"
      - "max_connections=300"
    environment:
      - DB_HOST=127.0.0.1
      - POSTGRES_DB=otpcrm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
